apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-dysk
spec:
  containers:
  - name: nginx-flex-dysk
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
  - name: test
    flexVolume:
      driver: "foo/dysk"
      secretRef:
        name: dyskcreds
      options:
        size: "5"
